### ISSUE TITLE
Land cover

### ISSUE THREAD

**Issue by Saadi4469** [lokendrarathore/vic-auto#3]
Hi Mr. Rathore,

Can you please share a link for the latest land cover file you used in vicauto.py? Can I use the following 30m land cover tiff?

![Land_Cover_Classes](https://user-images.githubusercontent.com/55733842/94634948-50d5e380-0286-11eb-9b82-85df7354b918.PNG)

Cheers,

**Comment by LSRathore** [comment]
This seems good to me. Just make sure that these land cover classes match with the classes in your vegetation library file.

**Comment by Saadi4469** [comment]
Thank you for your quick response Dr. Rathore, one further query is that will the script automatically create vegetation parameter file variables such as LAI?

**Comment by LSRathore** [comment]
This script creates the vegetation parameter file. But only these parameters are included -gridcel, Nveg, veg_class, Cv, root_depth and root_fract (parameter details- https://vic.readthedocs.io/en/master/Documentation/Drivers/Image/Params/#vegetation-parameter-file).

Note that, rest parameters like LAI, albedo, etc. are not included in the vegetation parameter file but given in the vegetation library file (just upload a sample vegetation library file).

**Comment by LSRathore** [comment]
For vegetation file preparation, I used the global land cover map GLC2000

**Comment by Saadi4469** [comment]
Dr. Rathore, how can I create a vegetation library file representative of the above mentioned land cover map GLC 2000? I do have a vegetation library file but that's only for the Columbia Basin in the US, and I don't know whether I can use that vegetation library file with this land cover map.

**Comment by LSRathore** [comment]
You can use any land use map with your own vegetation library file, you just need to verify that the land cover classes in your map are the same as classes mentioned in your vegetation library file.

**Comment by Saadi4469** [comment]
Thank you so much Dr. Rathore! I really appreciate your quick responses!

Stay safe and healthy,
Cheers,
