### ISSUE TITLE
Cell height and width

### ISSUE THREAD

**Issue by Saadi4469** [lokendrarathore/vic-auto#5]
Hi Dr. Rathore,

The scripts require to the cell height and width to be defined in degree, if I want a create a grid cell of 500 m by 500 m, how can I covert 500 m to its corresponding height and width in degree?

Thank you for creating these scripts,
Cheers,

**Comment by LSRathore** [comment]
I just assumed that 1 degree = 100 Km. So 500 m would be 0.005 degrees.

**Comment by Saadi4469** [comment]
Brilliant, thank you so much Dr. Rathore!
