### ISSUE TITLE
Elevation Bands

### ISSUE THREAD

**Issue by Saadi4469** [lokendrarathore/vic-auto#6]
Hi Dr. Rathore,

Hope you are doing well, can you please explain that what logic does the code use to distribute the elevation bands in a particular grid cell? From what I understand the user defines the number of bands, and then the code calculates the fractional area of the cell. But, how does the code determine that a grid cell will have 1 or 2 or more bands. And lastly is the code following a defined interval in elevation change from one band to the next band as we define in a contour?
Thank for your continued guidance!

**Comment by LSRathore** [comment]
In the script, the user defines the number of bands in each grid cell. Then it takes equal elevation intervals between the minimum and maximum elevation of the raster. In code line 226, you can see the code defining the elevation ranges. Then for each range, it checks if that elevation range exists in the grid, if yes then calculates fractional area, if not then the fraction area is considered zero.

The band ranges would be the same for each grid. Suppose your elevation raster has a minimum elevation value 600 m and a maximum of 1600 m and you define a total of 10 numbers of elevation bands to be considered.

For the given values, it calculates the elevation interval as 1600-600 / 10 = 100 and makes 10 elevation ranges between 600 to 1600 on an equal interval of 100 m.

Hope this clears your doubt.

**Comment by Saadi4469** [comment]
Thanks a bundle Mr. Rathore!
